# 1. Importando Bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 2. Analisando o dataset

In [2]:
df = pd.read_csv('data/telecom_customer_churn.csv', delimiter=',')

In [4]:
df.shape

(7043, 38)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 38 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   str
 1   Gender                             7043 non-null   str
 2   Age                                7043 non-null   int64
 3   Married                            7043 non-null   str
 4   Number of Dependents               7043 non-null   int64
 5   City                               7043 non-null   str
 6   Zip Code                           7043 non-null   int64
 7   Latitude                           7043 non-null   float64
 8   Longitude                          7043 non-null   float64
 9   Number of Referrals                7043 non-null   int64
 10  Tenure in Months                   7043 non-null   int64
 11  Offer                              3166 non-null   str
 12  Phone Service                      7043 non-null   str
 13  Avg Monthly Long Distance Charges  6361 non-null   float64
 14  Multiple Lines                     6361 non-null   str
 15  Internet Service                   7043 non-null   str
 16  Internet Type                      5517 non-null   str
 17  Avg Monthly GB Download            5517 non-null   float64
 18  Online Security                    5517 non-null   str
 19  Online Backup                      5517 non-null   str
 20  Device Protection Plan             5517 non-null   str
 21  Premium Tech Support               5517 non-null   str
 22  Streaming TV                       5517 non-null   str
 23  Streaming Movies                   5517 non-null   str
 24  Streaming Music                    5517 non-null   str
 25  Unlimited Data                     5517 non-null   str
 26  Contract                           7043 non-null   str
 27  Paperless Billing                  7043 non-null   str
 28  Payment Method                     7043 non-null   str
 29  Monthly Charge                     7043 non-null   float64
 30  Total Charges                      7043 non-null   float64
 31  Total Refunds                      7043 non-null   float64
 32  Total Extra Data Charges           7043 non-null   int64
 33  Total Long Distance Charges        7043 non-null   float64
 34  Total Revenue                      7043 non-null   float64
 35  Customer Status                    7043 non-null   str
 36  Churn Category                     1869 non-null   str
 37  Churn Reason                       1869 non-null   str
dtypes: float64(9), int64(6), str(23)
memory usage: 2.0 MB

In [5]:
df.head(3)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices

In [6]:
df.describe()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,6361.000000,5517.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,25.420517,26.189958,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,14.200374,19.586585,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,1.010000,2.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,13.050000,13.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,25.690000,21.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,37.680000,30.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

## 2.1 Verificando nulos

In [7]:
df.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [13]:
df[
    (df['Internet Type'].isnull()) & 
    (df['Avg Monthly GB Download'].isnull()) & 
    (df['Online Security'].isnull()) & 
    (df['Online Backup'].isnull()) & 
    (df['Device Protection Plan'].isnull()) & 
    (df['Premium Tech Support'].isnull()) &
    (df['Streaming TV'].isnull()) &
    (df['Streaming Movies'].isnull()) &
    (df['Streaming Music'].isnull()) &
    (df['Unlimited Data'].isnull())
   ]['Internet Service'].value_counts()

Internet Service
No    1526
Name: count, dtype: int64

Os nulos nas colunas acima são explicados por não terem serviço de internet

In [17]:
df[df['Churn Category'] == 'Churned'].isnull().sum().sum()

np.int64(0)

In [18]:
df[df['Churn Reason'] == 'Churned'].isnull().sum().sum()

np.int64(0)

Essas duas variáveis acima explicam a variável churn, sendo assim vou optar por tirar elas do dataset no tratamento de dados

In [22]:
df['Phone Service'].value_counts()

Phone Service
Yes    6361
No      682
Name: count, dtype: int64

In [21]:
df[df['Multiple Lines'].isnull()]['Phone Service'].value_counts()

Phone Service
No    682
Name: count, dtype: int64

In [25]:
df[df['Avg Monthly Long Distance Charges'].isnull()]['Phone Service'].value_counts()

Phone Service
No    682
Name: count, dtype: int64

Os nulos de 'Multiple Lines' e 'Avg Monthly Long Distance Charges' são os 'No' em Phone Service

In [32]:
df['Offer']

0           NaN
1           NaN
2       Offer E
3       Offer D
4           NaN
         ...
7038    Offer D
7039    Offer D
7040    Offer E
7041    Offer A
7042        NaN
Name: Offer, Length: 7043, dtype: str

# 3. Tratamento de dados

In [37]:
df.drop(columns=['Customer ID', 'Churn Category', 'Churn Reason'], inplace=True)

In [39]:
df.duplicated().sum()

np.int64(0)

## 3.1 Tratando os nulos

In [42]:
df[['Internet Type', 'Avg Monthly GB Download', 'Online Security', 'Online Backup', 'Device Protection Plan', 'Premium Tech Support', 'Streaming TV', 'Streaming Movies', 'Streaming Music', 'Unlimited Data']] = df[['Internet Type', 'Avg Monthly GB Download', 'Online Security', 'Online Backup', 'Device Protection Plan', 'Premium Tech Support', 'Streaming TV', 'Streaming Movies', 'Streaming Music', 'Unlimited Data']].fillna('No Internet Service')

In [46]:
df[df['Phone Service'] == 'No'][['Avg Monthly Long Distance Charges', 'Multiple Lines']].value_counts()

Series([], Name: count, dtype: int64)

In [47]:
df[['Avg Monthly Long Distance Charges', 'Multiple Lines']] = df[['Avg Monthly Long Distance Charges', 'Multiple Lines']].fillna('No Phone Service')

In [49]:
df["Offer"] = df["Offer"].fillna("No Offer")

In [50]:
df.isnull().sum()

Gender                               0
Age                                  0
Married                              0
Number of Dependents                 0
City                                 0
Zip Code                             0
Latitude                             0
Longitude                            0
Number of Referrals                  0
Tenure in Months                     0
Offer                                0
Phone Service                        0
Avg Monthly Long Distance Charges    0
Multiple Lines                       0
Internet Service                     0
Internet Type                        0
Avg Monthly GB Download              0
Online Security                      0
Online Backup                        0
Device Protection Plan               0
Premium Tech Support                 0
Streaming TV                         0
Streaming Movies                     0
Streaming Music                      0
Unlimited Data                       0
Contract                             0
Paperless Billing                    0
Payment Method                       0
Monthly Charge                       0
Total Charges                        0
Total Refunds                        0
Total Extra Data Charges             0
Total Long Distance Charges          0
Total Revenue                        0
Customer Status                      0
dtype: int64